name: Extract Data from Appended File and Update Issue

on:
  issues:
    types: [opened]

jobs:
  extract-data-and-update-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Extract Data
        run: |
          # Get the issue number
          ISSUE_NUMBER=$(echo "${{ github.event.issue.number }}")
          # Get the contents of the appended file
          # The regular expression matches on a code block that has at least 20 lines
          APPENDED_FILE_CONTENTS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "${{ github.api_url }}/repos/${{ github.repository }}/issues/${ISSUE_NUMBER}/comments" | jq -r '.[] | select(.body | test("```.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*\n```"; "m")) | .body' | sed 's/```.*\n//g; s/```//g')
          # Parse the contents of the appended file to extract the required data
          Arma_Version=$(echo "$APPENDED_FILE_CONTENTS" | awk '/^Type:/{t=$0} /^Build:/{b=$0} /^Version:/{print t"\n"b"\n"$0}' | grep -oP '\d+\.\d+\.\d+')
          ACE_Version=$(echo "$APPENDED_FILE_CONTENTS" | grep -oP 'Advanced Combat Environment \K\d+\.\d+\.\d+')
          CBA_Version=$(echo "$APPENDED_FILE_CONTENTS" | grep -oP 'Community Base Addons v\K\d+\.\d+\.\d+')
          KAT_Version=$(echo "$APPENDED_FILE_CONTENTS" | grep -oP 'kat_main\.pbo - \K\d+\.\d+\.\d+\.\d+')
          Modlist=$(echo "$APPENDED_FILE_CONTENTS" | sed -n '/----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------/,/==========================================================================================================================================================================================================/ {/----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------/!{/==========================================================================================================================================================================================================/!p}}' | sed 's/^[0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}//' | awk -F '|' '{print $1}')
          # Update the issue with the extracted data
          printf -v EXTRACTED_DATA "Arma Version: %s\nACE Version: %s\nCBA Version: %s\nKAT Version: %s\nModlist: %s" "$Arma_Version" "$ACE_Version" "$CBA_Version" "$KAT_Version" "$Modlist"
          # curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X PATCH "${{ github.api_url }}/repos/${{ github.repository }}/issues/${ISSUE_NUMBER}" -d "{\"body\":\"Extracted data: ${EXTRACTED_DATA}\"}"